Resolve timer test
salcudeann/learn_ruby pull request #12
Opened 2021-07-19 07:15 UTC by salcudeann

2021-07-19 17:46 UTC, alexandru-calinoiu commented on 09_timer/timer.rb
> +  end
Ruby is a a very expresive language, you can surely find a better way to pad a string, take a look at [ruby docs](https://ruby-doc.org/).

Getting familiar with ruby docs will also help you way better that stack overflow on the long run.

2021-07-20 12:01 UTC, pirvudoru requested changes

2021-07-20 12:01 UTC, pirvudoru commented on 09_timer/timer.rb
> +    sec < 10 ? "0#{sec.to_s}" : sec.to_s
https://apidock.com/ruby/String/rjust

2021-07-20 12:01 UTC, pirvudoru commented on 09_timer/timer.rb
> +  def padded(sec)
Method names should be imperative verbs, since they do something. (in this case, `left_pad` or `pad`)

2021-07-20 12:01 UTC, pirvudoru commented on 09_timer/timer.rb
> +    end
```
"#{pad(hours)}:#{pad(minutes)}:#{pad(seconds)}"
```

Where hours / minutes / seconds are other methods or variables that are calculated based on the seconds instance variable.

2021-07-20 12:01 UTC, pirvudoru commented on 09_timer/timer.rb
> +  attr_writer :time_string
Why do you need to define a writer for time_string?

2021-07-20 12:01 UTC, pirvudoru commented on 09_timer/timer.rb
> +    end
Extract numbers and give them a name (these are called "magic numbers")

https://refactoring.guru/replace-magic-number-with-symbolic-constant

2021-07-21 13:07 UTC, alex-damian-negru approved these changes

2021-07-22 07:32 UTC, merged