Resolve dictionary test
salcudeann/learn_ruby pull request #13
Opened 2021-07-19 12:14 UTC by salcudeann

To run this problem, i had to change _be_true_ and _be_false_ from dictionary_spec.rb in _be_truthy_ and _be_falsey_.

2021-07-21 13:24 UTC, alex-damian-negru requested changes

2021-07-21 13:24 UTC, alex-damian-negru commented on 11_dictionary/dictionary.rb
> +      end
https://apidock.com/ruby/v2_6_3/Hash/merge check this out.

2021-07-21 13:24 UTC, alex-damian-negru commented on 11_dictionary/dictionary.rb
> +  def keywords()
The `()` are not required in ruby if there are no params.

2021-07-21 13:24 UTC, alex-damian-negru commented on 11_dictionary/dictionary.rb
> +    key_array.sort
There's a method in Ruby that allows you to fetch all the keys for a Hash, try to use that.

2021-07-21 13:24 UTC, alex-damian-negru commented on 11_dictionary/dictionary.rb
> +    @hash.has_key?(key) ? true : false
`has_key?(key)` already returns a bool.

2021-07-22 07:43 UTC, pirvudoru commented on 11_dictionary/dictionary.rb
> +    @hash.each { |k, v| key_array.push(k) }
Ahem... https://ruby-doc.org/core-3.0.1/Hash.html#method-i-keys

2021-07-22 07:43 UTC, pirvudoru commented on 11_dictionary/dictionary.rb
> +    @hash.has_key?(key) ? true : false
What are the possible values that `has_key?` can return? :wink:

2021-07-22 07:46 UTC, merged