Feature/04 pig latin
salcudeann/learn_ruby pull request #5
Opened 2021-07-15 07:55 UTC by salcudeann

2021-07-15 08:14 UTC, alex-damian-negru requested changes

2021-07-15 08:14 UTC, alex-damian-negru commented on 04_pig_latin/pig_latin.rb
> +$vow = ['a', 'e', 'i', 'o', 'u']
Variables declared with `$` are global. Don't use global variables.

2021-07-15 08:14 UTC, alex-damian-negru commented on 04_pig_latin/pig_latin.rb
> +$vow = ['a', 'e', 'i', 'o', 'u']
`vow` is unclear, better use the whole, pluralized name, e.g. `vowels`.

2021-07-15 08:14 UTC, alex-damian-negru commented on 04_pig_latin/pig_latin.rb
> +$con = ['b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'q', 'r', 's', 't', 'w', 'v', 'x', 'y', 'z']
Same here.

2021-07-15 08:14 UTC, alex-damian-negru commented on 04_pig_latin/pig_latin.rb
> +  str.split.map { |curr_word|  translate_word(curr_word) }.join(' ')
:+1:

2021-07-15 08:14 UTC, alex-damian-negru commented on 04_pig_latin/pig_latin.rb
> +  if $vow.include? word[0]
You an calso use [.start_with?](https://ruby-doc.org/core-3.0.2/String.html#method-i-start_with-3F).

2021-07-15 08:14 UTC, alex-damian-negru commented on 04_pig_latin/pig_latin.rb
> +    final_word += translate_vow(word)
I think the `final_word` variable isn't needed - try to find a solution that doesn't use it.

2021-07-15 08:14 UTC, alex-damian-negru commented on 04_pig_latin/pig_latin.rb
> +  end
We rarely use `while` in the Ruby world (I don't remember the last time I used it).

Can you find a solution that uses `each`, `map`, `split` (one or a combination of these)?

2021-07-16 06:15 UTC, pirvudoru commented on 04_pig_latin/pig_latin.rb
> +  else
Can you rewrite this to not make the first letter an exceptional case?

2021-07-19 11:08 UTC, pirvudoru approved these changes

2021-07-19 11:08 UTC, pirvudoru commented on 04_pig_latin/pig_latin.rb
> +  cons = ['b', 'c', 'd', 'f', 'g', 'h', 'j', 'k', 'l', 'm', 'n', 'p', 'q', 'r', 's', 't', 'w', 'v', 'x', 'y', 'z']
You could use 

```
vowels = ['a', 'e', 'i', 'o', 'u']
````

and 

```
de vowel?(char)
  vowels.inlcude(char)
end

def consonant?(char)
  !vowel?(char)
end
```

for a smaller array :))

2021-07-19 12:47 UTC, merged

2021-07-19 12:55 UTC, alex-damian-negru commented
@salcudeann Please merge the PRs only until after you've replied to or applied all the change suggestions here.